### ISSUE TITLE
Need a menu item type conditional on admin status

### ISSUE THREAD

**Issue by sliptonic** [JohnAD/fondum#29]
Would be nice to have a menu of admin only pages.
The menu should not display for anon users or logged in users who are not admin

**Comment by JohnAD** [comment]
So, similar to the optional `"logged_in"` key/value in a menu in the `general.json` file, add a `admin_only` key/value. A value of `false`, `null`, or missing would not require the user to be an administrator. A value of `true` would require it.

Example:
```
{
  "type": "link",
  "title": "Fancy Admin think",
  "url": "/account/sudo-manage/",
  "admin_only": true
},
```

**Comment by JohnAD** [comment]
Alternatively, a `Page` class can have a `admin_required` attribute. Not sure how that would be mapped back to the JSON doc. Or if it even should.

**Comment by JohnAD** [comment]
Added `admin_required` flag to `general.json` menus. Changed `logged_in` to `login_required` to match the `Page` class. Still not happy with that name though.
