### ISSUE TITLE
admin required bug

### ISSUE THREAD

**Issue by sliptonic** [JohnAD/fondum#35]
When I add 'admin_required = True' to a page, it works.

When I add   "admin_required": true to a menu item I get an error: 
I think pages are looking at g.user.admin and menus are looking at g.admin.

fondum_vendor.cutwonder.com_1  |   File "/site/views.py", line 63, in page_handler
fondum_vendor.cutwonder.com_1  |     if not g.admin_flag:
fondum_vendor.cutwonder.com_1  |   File "/usr/local/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
fondum_vendor.cutwonder.com_1  |     return getattr(self._get_current_object(), name)
fondum_vendor.cutwonder.com_1  | AttributeError: '_AppCtxGlobals' object has no attribute 'admin_flag'

**Comment by JohnAD** [comment]
fixed.
