### ISSUE TITLE
Tables without name.

### ISSUE THREAD

**Issue by sliptonic** [JohnAD/fondum#37]
Can't really do it.  If table name is not defined, then 'not defined' shows above the table.  If it's None, it actually renders the string "None" and if it's an empty string, it shows a border.  

It should be possible to have a page table without a name.

Likewise, a page without a 'default text'  or where 'default text = """""" it literally renders "Page Not Found" It should render nothing at all

**Comment by JohnAD** [comment]
If there is only one table and the name of the table is empty, then the table tabs are not rendered.

Leaving ticket open as I've not yet fixed the Page Not Found problem.
