### ISSUE TITLE
Display fields without label

### ISSUE THREAD

**Issue by sliptonic** [JohnAD/fondum#46]
If a field is created like:
s_street_line_one = DisplayTextField("Address")
then the label is 'Address'

If the field is created like:
s_street_line_one = DisplayTextField()
The the label is 'S Street Line ONe'

So how can I create a field where NO label is shown?  This is particularly an issue for DisplayPictureField where I wish to show the image not the label or name associated with the field.
 vendorlogo = DisplayPictureField()

**Comment by JohnAD** [comment]
I might have already accidentally fixed this.

If the field label is missing, PageForm auto-creates one. But if you give it an explicitly empty label, that should work:

`vendorlogo = DisplayPictureField("")`

I've tested this on both Forms and Tables.
