### ISSUE TITLE
Copy_fields bugs

### ISSUE THREAD

**Issue by sliptonic** [JohnAD/fondum#50]
The new copy-fields logic has some fairly serious bugs.

First, If the models defines the field like:
n_material_thickness = db.FloatField(label="Material Thickness")

It still becomes a StringField on the page.  Thus the database upsert fails because it's expecting a float.

Next I defined a bunch of fields like:
s_mr_name = db.StringField(label="Maker Redux Name", display_only=True)
The fields are displayed read-only on the page but on upsert, the read-only data is destroyed.

**Comment by JohnAD** [comment]
Fixed FloatField. DecimalField needs testing but might work. BTW, there are 26 more (mostly obscure) fields left to interpret. I haven't a clue how to handle ME's `MultiPolygonField` field. :)

`display_only=True` fields now generate hidden fields to solve the problem described. Let me know if you see any complication.

Also, I now support a `hide=True` parameter from ME documents. That makes the field a hidden field, regardless of type. However, if `_field_order` is used, then the hidden fields must still be included for the hidden fields to be generated in the form.
